# Generated by Django 2.2.3 on 2019-11-06 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sems', '0020_auto_20180622_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(choices=[('9:00', '9:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:10', '12:10'), ('13:10', '13:10'), ('14:10', '14:10'), ('15:10', '15:10'), ('16:10', '16:10'), ('17:20', '17:20'), ('18:30', '18:30'), ('19:30', '19:30'), ('20:20', '20:20')], max_length=5)),
                ('end_time', models.CharField(choices=[('9:50', '9:50'), ('10:50', '10:50'), ('11:50', '11:50'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:10', '18:10'), ('19:20', '19:20'), ('20:20', '20:20'), ('21:20', '21:20')], max_length=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sems.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
