# Generated by Django 2.2.3 on 2019-11-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sems', '0021_schedule'),
    ]

    operations = [
    ]
