# Generated by Django 2.2.3 on 2019-11-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sems', '0022_auto_20191107_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10),
        ),
    ]
